# Generated by Django 4.1.7 on 2025-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('account', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('recurrence', models.CharField(choices=[('one-time', 'One-time'), ('recurring', 'Recurring')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='transactions/')),
            ],
        ),
    ]
