# Generated by Django 5.2.3 on 2025-06-26 11:17

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='file',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='persian_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=7),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('home_utilities', 'Home & Utilities'), ('transportation', 'Transportation'), ('food', 'Food'), ('health_insurance', 'Health & Insurance'), ('savings_debt', 'Savings & Debt'), ('personal_family', 'Personal & Family'), ('leisure', 'Leisure'), ('salary', 'Salary'), ('personal_business', 'Personal Business'), ('other', 'Other')], default=core.models.Transaction.default_category, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags_events',
            field=models.ManyToManyField(blank=True, related_name='transactions_by_event', to='core.event'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags_people',
            field=models.ManyToManyField(blank=True, related_name='transactions_by_person', to='core.person'),
        ),
    ]
