# Generated by Django 5.2.3 on 2025-06-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_person_remove_transaction_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='persian_date',
        ),
    ]
