# Generated by Django 5.2.3 on 2025-08-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='last_checked',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
