# Generated by Django 5.2.3 on 2025-08-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_client_uuid_event_deleted_at_event_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp', null=True),
        ),
    ]
